services:
  - type: web
    name: "MoviesMosaic"
    env: python
    buildCommand: |

      echo "📦 Installing packages..."
      pip install -r requirements.txt

      echo "📋 Checking migrations..."
      python manage.py showmigrations

      echo "🧱 Applying migrations..."
      python manage.py migrate --noinput --verbosity 3

      echo "🎨 Collecting static files..."
      python manage.py collectstatic --no-input

    startCommand: gunicorn MoviesMosaic.wsgi:application
    envVars:
      - key: DATABASE_URL
        value: "sqlite:///db.sqlite3"
      - key: DJANGO_SECRET_KEY
        value: "your-actual-50-char-secret-key"
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: "moviesmosaic-43jp.onrender.com"



